# Generated by Django 3.2.7 on 2023-02-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время  провождения')),
                ('name', models.CharField(max_length=127, verbose_name='назвние ')),
                ('location', models.CharField(max_length=127, verbose_name='локации')),
                ('image', models.ImageField(upload_to='event/images/', verbose_name='картинки')),
                ('description', models.TextField(verbose_name='описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'мкроприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
    ]
