# Generated by Django 3.2.7 on 2023-02-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacanci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='назвние ')),
                ('post', models.CharField(max_length=127, verbose_name='Должность')),
                ('selery', models.CharField(max_length=127, verbose_name='Оклад')),
                ('type_work', models.CharField(max_length=127, verbose_name='тип')),
                ('description', models.TextField(verbose_name='описание')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('сompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacances', to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
