# Generated by Django 3.2.7 on 2023-02-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='company/logos/', verbose_name='логотип компании')),
                ('name', models.CharField(max_length=127, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('telegram', models.URLField(verbose_name='телеграм')),
                ('whatsapp', models.URLField(verbose_name='вотс апп')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
    ]
